# Generated by Django 3.2.4 on 2021-08-03 21:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('type', models.IntegerField(choices=[(1, 'foundation'), (2, 'non-governmental organization'), (3, 'local collection')], default='foundation')),
                ('categories', models.ManyToManyField(to='used.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('address', models.CharField(max_length=250, null=True)),
                ('phone_number', models.IntegerField(null=True)),
                ('city', models.CharField(max_length=64)),
                ('zip_code', models.CharField(max_length=64, null=True)),
                ('pick_up_date', models.DateField(blank=True)),
                ('pick_up_time', models.DateTimeField(blank=True)),
                ('pick_up_comment', models.CharField(blank=True, max_length=150)),
                ('categories', models.ManyToManyField(to='used.Category')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='used.institution')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
