# Generated by Django 3.2.4 on 2021-08-11 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('used', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='pick_up_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='donation',
            name='pick_up_time',
            field=models.DateTimeField(),
        ),
    ]
