# Generated by Django 3.2.4 on 2021-07-27 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('used', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('type', models.IntegerField(choices=[(1, 'foundation'), (2, 'non-governmental organization'), (3, 'local collection')], default='foundation')),
                ('categories', models.ManyToManyField(to='used.Category')),
            ],
        ),
    ]
